### ISSUE TITLE
Query for "serotonin gpcr" does not return anything 

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#1]
**Steps taken** 
Go to the datamed.biocaddie.org interface
Enter "serotonin gpcr"
(do not enter the quotes - they are just here to make it clear what the actual query is).
Press enter/return - or click Go

**Results**
No results are returned.

**Expected results**
In contrast the elastic search endpoint returns 198 results to the query
GET /biocaddie/pdb/_search?q='serotonin gpcr'

**Comment by RuilingLiu** [comment]
datamed.biocaddie.org points to UTHealth's elastic search endpoint. 

To compare the results with UCSD's elastic search endpoint. Please use this link: http://datamed.biocaddie.org/ucsd/. It will return 3 results.

The reason why it only returns 3 results is because we use "multi_match" instead of "simple_query_string". 

If we use "simple_query_string"
1.  search "serotonin", the endpoint returns 50 results;
2.  search "gpcr", the endpoint returns 151 results;
3.  search "serotonin gpcr", the endpoint returns 198 results.

Since search engines are supposed to return more specific results. Lung -> lung cancer -> lung cancer chemotherapy ->lung cancer chemotherapy side effects, ... Adding new words should get us closer to our target. 

That's why we use "multi_match", it returns more specific results.

**Comment by jgrethe** [comment]
The multi_match does return more specific results.  However, depending on the configuration of the multi_match (e.g. best_fields which searches for the multiple words in the same field using a match query wrapped in a dis_max query) you may end up with too small a result set - as a number of queries will need to search for the words across fields.  best_fields is the default and this applies well to textual documents.  However, for data documents we probably want to utilize the cross_fields query type: "the cross_fields type is particularly useful with structured documents where multiple fields should match".

For the simple query the default is an OR.  What you will see here is that the top 3 documents returned have GPCR and serotonin - the remainder of the documents have just serotonin with a lower score.  if you do a simple boolean query - you get the 3 results with a co-occurence of the terms:

{
"query": {
"bool": {
"must": [
{
"query_string": {
"default_field": "_all",
"query": "serotonin"
}
}
,
{
"query_string": {
"default_field": "_all",
"query": "gpcr"
}
}
],
"must_not": [ ],
"should": [ ]
}
},
"from": 0,
"size": 10,
"sort": [ ],
"facets": { }
}

**Comment by ianfore** [comment]
This has started a good discussion. I think three threads arise from it.
1. We need to understand which UI URLs are pointing at which elasticsearch. Rather than explain that in text here an architectural diagram would probably convey it most clearly. e.g. it would show if datamed.biocaddie.org/ucsd points at a different elasticsearch endpoint, and whether it is a completely separate instance of the UI. 
2. If datamed.biocaddie.org is pointing to a different elasticsearch endpoint then read only access to that endpoint would be useful in understanding the UI behavior.
3. The statement "search engines are supposed to return more specific results" is true in general terms. One reason for getting the discussion going is whether the specificity matches what users want. We can only do that by users trying it out here and providing feedback whether they get back what they think they should. The aim would then be some iteration to get to behavior that matches what users want.

**Comment by ianfore** [comment]
This is closely connected with #45 . These threads both contain useful perspectives on the issues of how a user enters a multiple word query. Let's continue the dialog in #45 .

Still not clear that we have consensus of how this should work. Is there something that "most" users would prefer.
