### ISSUE TITLE
display persistent identifier for dataset in detail view

### ISSUE THREAD

**Issue by mfenner** [biocaddie/prototype_issues#113]
I don't see this information for datasets from Dryad.

**Comment by ryscher** [comment]
The persistent identifiers appear as the "Download URL" for core Dryad content... This label is a bit confusing, since the identifier points to a landing page instead of a direct download.

This issue is compounded by items that are harvests of harvests. These items do not display identifiers. (Filed separately as https://github.com/biocaddie/prototype_issues/issues/117)

**Comment by tjohnson250** [comment]
Has this been corrected? When we first launched the links to Dryad went to the Dryad home page, but since around 2 days after launch, they started going directly to the download page for the dataset.

**Comment by NinaSalimi** [comment]
This issue has been fixed.
