### ISSUE TITLE
Incomplete data on Zika?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [biocaddie/prototype_issues#147]
I was surprised to see that a search for "Zika" or "Zika virus" yielded zero results, even via advanced search:
https://datamed.org/search.php?searchtype=data&query=%22Zika+virus%22[All+Search+Fields] .
Given the databases already integrated with DataMed, I would have expected some more to show up. Some hints via https://sis.nlm.nih.gov/dimrc/zikavirus.html .

**Comment by soysal** [comment]
This is correct. There is no research dataset on Zika in indexed datasources in version 1.0. With the next data update, we'll have one new dataset generated on April 27, 2016 from Dryad, entitled "Data from: Zika Virus in the Americas: early epidemiological and genetic findings". But, since it's a new thread, probably there is no available data yet..

**Comment by aegururaj** [comment]
Also want to note that "Scientific Data", that is in the pipeline for indexing by DataMed, had a recent call for call for submission of Zika virus related datasets (please see http://blogs.nature.com/scientificdata/2016/01/20/call-for-submissions-zika-virus-related-datasets/). So we should see more datasets coming up if the datasets are available via Scientific Data.

**Comment by NinaSalimi** [comment]
@Daniel-Mietchen thanks for your feedback.
