### ISSUE TITLE
Testing the "contact us" page

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#170]
Part of testing 1.5

**Comment by ianfore** [comment]
This is testing that the link to GitHub works. Closing.
Perhaps we should have a label to mark these kinds of items because otherwise they inflate the number of real issues that have been fixed. I think I've seen five of them now
The "Invalid" label looked like one to consider - but it isn't really the right meaning.
I would suggest "artifact" is a suitable label that could be used for these items.
