### ISSUE TITLE
Unexpected results from LINCS data searches

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#82]
This issue has been reported by a Jeff Grethe.

Here seem to be some funky results searching for LINCS data:

Search for ‘Cell Proliferation’ and don’t get any results even though cell proliferation is in the record (from the main search).  
http://datamed.biocaddie.org/search.php?query=cell+proliferation&searchtype=data

![pastedgraphic-3](https://cloud.githubusercontent.com/assets/6471104/14471759/a177e28e-00b5-11e6-9497-c066e59853b5.png)

However, when on LINCS the search works...
http://datamed.biocaddie.org/search-repository.php?query=Cell+proliferation&repository=0004&searchtype=data

![pastedgraphic-4](https://cloud.githubusercontent.com/assets/6471104/14471766/a6d9141e-00b5-11e6-8b51-783bbe9054b2.png)

And it seems it may have to do with the capitalization - for some reason the interface capitalizes certain words when I type (main search bar capitalizes every word).  So the query above - if changed to:
http://datamed.biocaddie.org/search-repository.php?query=cell+proliferation&repository=0004&searchtype=data

doesn’t return any results.  So search seems to be case sensitive in certain instances - which it probably shouldn’t be.

And the original query from the main search bar if changed does return results:
http://datamed.biocaddie.org/search.php?query=Cell+proliferation&searchtype=data

**Comment by naturalbeau** [comment]
The problem has been fixed. It is because of the mapping of the fields in ES. The "biological process" field was indexed as "not_analyzed" due to we use it as a facet field. So the query "cell proliferation" does not match to this field but "Cell proliferation" does. Now this field has been changed to "multi field" type and can be searched as "analyzed" but facets as a whole phrase. It is also done for other facet fields in LINCS. I will examine all the other data repositories in the UI and fix the same problem.
